name: CI/CD

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions:
  deployments: write
  contents: write
  statuses: write
  actions: write
  checks: read

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.3.1]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: dmaximyuk/dev
          token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
          fetch-depth: 0

      - name: Setup Node.js v${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: 'Preparing blueprint-environment'
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
          repository: dmaximyuk/rabotyaga-frontend
          path: rabotyaga-frontend

      - name: Install dependencies
        working-directory: rabotyaga-frontend
        run: npm i

      - name: Create build
        working-directory: rabotyaga-frontend
        run: npm run build

      - name: Deploy
        working-directory: rabotyaga-frontend
        run: |
          git config --global user.name ${{ env.user_name }}
          git config --global user.email ${{ env.user_email }}
          git remote set-url origin https://${github_token}@github.com/${repository}
          npm run deploy
        env:
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
          github_token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
          repository: "dmaximyuk/dev"
          repository_old: ${{ github.repository }}
