name: CI/CD

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.3.1]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js v${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm i

      - name: Create build
        run: npm run build

      - name: Deploy
        run: |
          npm run deploy
#          git config --global user.name "${{ env.user_name }}"
#          git config --global user.email "${{ env.user_email }}"
#          git clone https://${{ env.github_token }}@github.com/${{ env.destination_repository }} dep_rep
#          cd dep_rep
#          rm -rf *
#          cp -r ../dist/* .
#          git add .
#          git commit -m "Deploy build from source repository"
#          git push origin master
        env:
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
          github_token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
          destination_repository: "dmaximyuk/dev"
