name: CI/CD

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions:
  deployments: write
  contents: write
  statuses: write
  actions: write
  checks: read

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.3.1]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
          fetch-depth: 0

      - name: Setup Node.js v${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm i

      - name: Create build
        run: npm run build

      - name: Deploy
        run: |
          git config --global user.name ${{ env.user_name }}
          git config --global user.email ${{ env.user_email }}
          git remote add dev_repository https://${{ env.github_token }}@github.com/dmaximyuk/dev
          git add -f dist
          git status
          if [[ -n $(git diff README.md) ]]; then
            git add README.md
            git commit -m "Actions Generated Readme"
            echo "DONE=true" >> $GITHUB_OUTPUT
          else
            echo "README is the same. Nothing to commit."
          fi
          git commit -m "Deploy build from source repository"
          git push origin `git subtree --prefix dist master`:master --force
        env:
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
          github_token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
